root: true
env:
    es2022: true
    node: true
extends: eslint:recommended
rules:
    indent:
        - error
        - tab
        - SwitchCase: 1
    linebreak-style:
        - error
        - unix
    quotes:
        - error
        - single
        - allowTemplateLiterals: true
    semi:
        - warn
        - never
    no-self-compare: error
    no-constant-binary-expression: error
    no-unreachable-loop: error
    no-unused-vars:
        - error
        - varsIgnorePattern: "^_$"
    no-unused-private-class-members: error
    no-constructor-return: error